### ISSUE TITLE
Agent terminates on error

### ISSUE THREAD

**Issue by sriniketh923** [jhunt/go-sfab#10]
The agent terminates the connection if the handler return an error. I might still want to keep the connection alive but just log the error.

**Comment by jhunt** [comment]
This might just be a disconnect as to how handler is supposed to return; I will investigate this weekend.

**Comment by sriniketh923** [comment]
For SHIELD I was able to fix this error by always returning nil and I propagate the error back to SHIELD. It would make sense to me why the agent terminates on handler error if there was such a case that the agent should fail. But at least in our use case, the agent doesn't need to terminate as it was not the handler's fault for the failure. So this could potentially be a feature.

**Comment by jhunt** [comment]
Yes, this is intended behavior.

Per the docs (https://godoc.org/github.com/jhunt/go-sfab#Handler):

> A Handler function returns two values: a Unix-style integer exit code, and an error that (if non-nil) will terminate the Agent's main loop.

The SHIELD solution is the correct one; errors in that context are not transport errors, but are in fact semantic application-level errors and should be handled out-of-band.  The only time we should return an error in the handler is if we don't understand the protocol the hub is speaking, the messages don't make sense, or something unrecoverable has happened in the course of our duties as an sfab agent.
