### ISSUE TITLE
Agent fails to connect to hub

### ISSUE THREAD

**Issue by sriniketh923** [jhunt/go-sfab#9]
The HUB doesn't seem to delete the agent-identity or the fingerprint after an agent terminates it's connection. If the disconnected agent tries to connect back, the hub refuses the connection.

**Comment by jhunt** [comment]
I think there's a larger problem in detecting disconnects from agents.  I'll investigate tonight.

**Comment by jhunt** [comment]
Fixed in c45e3bc
